import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def generate_provenance_audit():
    os.makedirs('reports', exist_ok=True)
    report = """# Synthetic Data Provenance Audit

## 1. Where data.csv came from
`data.csv` was programmatically generated by the script `generate_sample_data.py`. The data loader (`data_loader.py`) is designed to automatically trigger this generator as a fallback if `data.csv` does not exist in the root folder.

## 2. Real SGCC Dataset Presence
The real SGCC dataset (which contains ~42,000 customers) is **not present** anywhere in the local repository. A search for `.csv` or compressed archives yielded only the 1,500-row synthetic `data.csv` and its generated downstream artifacts. 

## 3. Synthetic Generator Logic (`generate_sample_data.py`)
- **Normal Customers**: Generated using a baseline uniform random value (5 to 30) added to a sinusoidal seasonal base curve (simulating summer peaks) with 15% random normally-distributed Gaussian noise.
- **Theft Customers**: Theft cases are created by picking normal load profiles and deterministically injecting one of four extreme "theft" mathematical transformations:
  - `zeroing`: Hardcodes all daily consumption values to 0.0 after a random start day.
  - `scaling`: Multiplies consumption by a huge reduction factor (e.g. down to 10%-35% of original).
  - `partial_bypass`: Forces a 60% probability of dropping any given day's consumption to exactly 0.0.
  - `intermittent`: Forces 40% of the customer's days to exactly 5% of their original value.
- **FLAG Assignment**: `FLAG` is explicitly assigned 1 for these synthetically tampered rows.
- **Noise**: While base loads have some Gaussian noise, the theft injections (`0.0` replacements, extreme scaling) are deterministic structural shocks that bypass the noise completely.
- **Class Distribution**: The `theft_ratio` was manually hardcoded to 9% to mimic the genuine SGCC dataset class imbalance.

## 4. Why Engineered Features perfectly predict FLAG
The feature engineering pipeline extracts attributes like `zero_ratio`, `peak_to_average_ratio`, `min`, `cv`, and `longest_zero_streak`. 
Because the synthetic generator deterministically forces values to `0.0` or applies severe mathematical scalings to the theft class, the theft rows mathematically guarantee extreme outlier values for these engineered features compared to the normal class. Any ML algorithm will find these deterministic separations immediately.
"""
    with open('reports/Synthetic_Data_Provenance_Audit.md', 'w') as f:
        f.write(report)
        
def run_separability_audit():
    df = pd.read_csv('data/processed/sgcc_features.csv')
    
    # Target and Features
    target = 'FLAG'
    features = [c for c in df.columns if c not in ['CONS_NO', target]]
    
    # Calculate stats per class
    stats_df = df.groupby(target)[features].agg(['mean', 'median', 'std', 'min', 'max']).T
    stats_df.columns = ['Normal_0', 'Theft_1']
    
    # Flatten multi-index
    stats_df = stats_df.reset_index()
    stats_df.rename(columns={'level_0': 'Feature', 'level_1': 'Statistic'}, inplace=True)
    
    # Pivot to wide format
    audit_df = stats_df.pivot(index='Feature', columns='Statistic', values=['Normal_0', 'Theft_1'])
    audit_df.columns = [f'{col[0]}_{col[1]}' for col in audit_df.columns]
    
    # Calculate Standardized Mean Difference (Cohen's d roughly)
    audit_df['mean_diff'] = audit_df['Theft_1_mean'] - audit_df['Normal_0_mean']
    pooled_std = np.sqrt((audit_df['Normal_0_std']**2 + audit_df['Theft_1_std']**2) / 2)
    audit_df['Standardized_Mean_Diff'] = audit_df['mean_diff'] / (pooled_std + 1e-6)
    
    audit_df.to_csv('reports/SGCC_Class_Separability_Audit.csv')
    
    # Generate Plots for highly separable features
    os.makedirs('graphs/data_audit', exist_ok=True)
    
    top_features = ['zero_ratio', 'peak_to_average_ratio', 'cv', 'min', 'mean_abs_daily_change']
    
    for feat in top_features:
        plt.figure(figsize=(8, 5))
        sns.boxplot(x=target, y=feat, data=df)
        plt.title(f'Distribution of {feat} by Target Class')
        plt.tight_layout()
        plt.savefig(f'graphs/data_audit/dist_{feat}.png')
        plt.close()
        
    print("[SUCCESS] Separability Audit Complete.")

if __name__ == '__main__':
    generate_provenance_audit()
    run_separability_audit()

